Enable use of direction to app
abrensch/brouter pull request #464
Opened 2022-09-29 16:34 UTC by afischerdev

Enable use of direction to app #314

2022-09-30 07:32 UTC, devemux86 commented
So with this fix, we will be able to use the "direction" parameter with the Android service interface,
like the "heading" parameter in the website: changing the 1st turn instruction instead of the route?

Android and website will have different parameters: "direction" and "heading"?
As mentioned in the other issue, the "direction" does not work on the website:
https://github.com/abrensch/brouter/issues/314#issuecomment-1260981720

2022-09-30 16:59 UTC, afischerdev commented
> Android and website will have different parameters: "direction" and "heading"?
As mentioned in the other issue, the "direction" does not work on the website:

Yes, that is still the way it goes.
Because I have no different result over the brouter web client. Not sure if there is an extra handling for heading.
Your sample wasn't working for me. So I made an own [sample](http://brouter.de/brouter-web/#map=16/49.9507/8.7022/standard&lonlats=8.703382,49.951496;8.692053,49.947948&heading=0) that doesn't work on the website but offline with lib 1.6.3 and 1.6.4 it worked like expected.  

It can also be tested via direct call:
[heading=0](https://brouter.de/brouter?lonlats=8.703382,49.951496|8.692053,49.947948&profile=trekking&alternativeidx=0&format=gpx&timode=3&heading=0)
[heading=180](https://brouter.de/brouter?lonlats=8.703382,49.951496|8.692053,49.947948&profile=trekking&alternativeidx=0&format=gpx&timode=3&heading=180)

2022-09-30 17:31 UTC, devemux86 commented on brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl
> +    //  "direction"       = angle (optional to give a route a start direction)
Isn't the 1st section about the Android parameters, so we should include the "direction"?
And the 2nd section about the website parameters,  so we should include the "heading"?

2022-09-30 17:31 UTC, devemux86 commented
> Your sample wasn't working for me.

If we remove the "format=gpx", my last samples can be seen in the browser (same route, different 1st instruction):
[heading=0](https://brouter.de/brouter?lonlats=13.388700485229478,52.517017364501946%7C13.390865999999981,52.516046&heading=0&profile=car-fast&alternativeidx=0&timode=3) (u-turn)
[heading=180](https://brouter.de/brouter?lonlats=13.388700485229478,52.517017364501946%7C13.390865999999981,52.516046&heading=180&profile=car-fast&alternativeidx=0&timode=3) (straight)

2022-10-01 10:17 UTC, afischerdev commented
> Isn't the 1st section about the Android parameters, so we should include the "direction"?
And the 2nd section about the website parameters, so we should include the "heading"?

No, the aidl is the discription of the whole interface to the app. It has two section to make clear old / new interface.
But to make it equal I will replace direchtion with heading - cause this is already working and there is no app that uses direction - it is not working without this PR. 

> If we remove the "format=gpx", my last samples can be seen in the browser (same route, different 1st instruction):

Yes, I know. but it isn't a funny use case go the same way with different instructions. Anyway it shows 'heading' is recognized by the server.
My use case for this feature is: design a route, start route in app, on a right turn  go left (or what ever), app should notice it and reroute with the new heading. And then I don't want to hear a u-turn.

2022-10-06 10:54 UTC, afischerdev commented
@zod 
What do you think should we add this first or should I add this to the first peace of 1.6.4 updates. I plan to start with the new interface variables. That contains also aidl and BRouterWorker.

2022-10-18 05:13 UTC, zod commented
According to `git blame` the `direction` parameter is used by locus (fdf06cbdd00bcb1d7f423dc40d218f06f6660970). I think we should deprecate `direction` but still support it.

2022-10-18 05:14 UTC, zod requested changes
According to `git blame` the `direction` parameter is used by locus (fdf06cbdd00bcb1d7f423dc40d218f06f6660970). I think we should deprecate `direction` but still support it.

2022-10-18 09:38 UTC, afischerdev commented
@zod
Yes, you are right.
But when I changed this I found that it needs a
`rc.forceUseStartDirection = true;`
otherwise it is only used on recalc and not on start
[please see ](https://github.com/abrensch/brouter/blob/51dc7fb1fbc310796fba8b76e3c92b1b3b935891/brouter-core/src/main/java/btools/router/RoutingEngine.java#L615)
I don't know what was the intention in the old days to add this and if it is still used. But in my eyes I would like to get a route  that starts on North when I define a direction/heading North.
But when there is a deeper sense we could hold both in the app.

2022-10-18 11:47 UTC, abrensch commented
>> I don't know what was the intention in the old days
>> to add this and if it is still used. But in my eyes I would
>> like to get a route that starts on North when I define a
>> direction/heading North. But when there is a deeper
>> sense we could hold both in the app.

there's only "direction" in the api, not the speed,  but direction is undefined at low speed.

So it's a hack to restrict the usage of "direction" for recalculations, where this is most needed (to put a bias on the forward solution). Correct solution would be a cutoff on speed.

2022-10-18 15:17 UTC, afischerdev commented
@abrensch 
Ok, good to know. 
With the new change this should work again - Locus still sends direction.
And when using 'heading' it works from the beginning - only tested on lib 1.6.4.

2022-10-19 19:12 UTC, merged